# Generated by Django 5.1.7 on 2025-05-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('institutions', '0002_remove_institution_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='institutions.institution', verbose_name='Organizer'),
        ),
    ]
