# Generated by Django 5.1.7 on 2025-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_profile_pic_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('blocked', 'Bloqué')], default='pending', max_length=20, verbose_name='Statut du compte'),
        ),
    ]
