# Generated by Django 5.1.7 on 2025-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, choices=[('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'Traitement du Langage Naturel (NLP)'), ('computer_vision', 'Vision par Ordinateur'), ('reinforcement_learning', 'Apprentissage par Renforcement'), ('ai_ethics', "Éthique de l'IA"), ('robotics', 'Robotique et IA'), ('neural_networks', 'Réseaux de Neurones'), ('ai_security', "Sécurité de l'IA"), ('ai_healthcare', 'IA en Santé'), ('ai_finance', 'IA en Finance'), ('ai_education', 'IA en Éducation'), ('ai_transport', 'IA dans les Transports'), ('ai_agriculture', 'IA en Agriculture'), ('ai_energy', "IA dans l'Énergie"), ('ai_manufacturing', 'IA dans la Production'), ('ai_research', 'Recherche Fondamentale en IA'), ('autre', "Autre Domaine de l'IA")], max_length=50, null=True, verbose_name='Spécialité'),
        ),
    ]
