# Generated by Django 5.1.7 on 2025-05-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_verified_alter_customuser_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du blocage'),
        ),
    ]
