# Generated by Django 5.1.7 on 2025-05-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_block_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='block_reason',
        ),
    ]
