# Generated by Django 5.1.7 on 2025-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_banneduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
