# Generated by Django 5.1.7 on 2025-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_alter_comment_options_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_files/%Y/%m/%d/', verbose_name='Fichier'),
        ),
    ]
