# Generated by Django 5.1.7 on 2025-05-28 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='date')),
                ('users_count', models.IntegerField(default=0, verbose_name="nombre d'utilisateurs")),
                ('publications_count', models.IntegerField(default=0, verbose_name='nombre de publications')),
                ('corpora_count', models.IntegerField(default=0, verbose_name='nombre de corpus')),
                ('tools_count', models.IntegerField(default=0, verbose_name="nombre d'outils")),
                ('projects_count', models.IntegerField(default=0, verbose_name='nombre de projets')),
                ('forum_posts_count', models.IntegerField(default=0, verbose_name='nombre de messages forum')),
                ('visits_count', models.IntegerField(default=0, verbose_name='nombre de visites')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='nombre de téléchargements')),
            ],
            options={
                'verbose_name': 'statistique',
                'verbose_name_plural': 'statistiques',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=10, verbose_name='Ancien statut')),
                ('new_status', models.CharField(max_length=10, verbose_name='Nouveau statut')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-change_date'],
            },
        ),
    ]
