# Generated by Django 5.1.7 on 2025-05-17 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='date')),
                ('users_count', models.IntegerField(default=0, verbose_name="nombre d'utilisateurs")),
                ('publications_count', models.IntegerField(default=0, verbose_name='nombre de publications')),
                ('corpora_count', models.IntegerField(default=0, verbose_name='nombre de corpus')),
                ('tools_count', models.IntegerField(default=0, verbose_name="nombre d'outils")),
                ('projects_count', models.IntegerField(default=0, verbose_name='nombre de projets')),
                ('forum_posts_count', models.IntegerField(default=0, verbose_name='nombre de messages forum')),
                ('visits_count', models.IntegerField(default=0, verbose_name='nombre de visites')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='nombre de téléchargements')),
            ],
            options={
                'verbose_name': 'statistique',
                'verbose_name_plural': 'statistiques',
                'ordering': ['-date'],
            },
        ),
    ]
