# Generated by Django 5.1.7 on 2025-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='response',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='response_given',
            field=models.BooleanField(default=False),
        ),
    ]
