# Generated by Django 5.1.7 on 2025-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_notificatio_recipie_9c8dcc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
