# Generated by Django 5.1.7 on 2025-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
