# Generated by Django 5.1.7 on 2025-05-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0004_notification_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('PROJECT_INVITATION', 'Invitation à un projet'), ('MEMBERSHIP_REQUEST', "Demande d'adhésion"), ('PROJECT_UPDATE', 'Mise à jour de projet'), ('TASK_ASSIGNED', 'Tâche assignée'), ('COMMENT', 'Commentaire')], default='SYSTEM', max_length=50),
        ),
    ]
