# Generated by Django 5.1.7 on 2025-04-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='is_approved',
        ),
    ]
