# Generated by Django 5.1.7 on 2025-04-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='nlptool',
            name='access_type',
        ),
    ]
