# Generated by Django 5.1.7 on 2025-05-18 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_corpus_access_type_remove_course_access_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Auteurs'),
        ),
    ]
