# Generated by Django 5.1.7 on 2025-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_document_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AddField(
            model_name='course',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AddField(
            model_name='document',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
    ]
