# Generated by Django 5.1.7 on 2025-04-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_corpus_mots_cles_cours_mots_cles_outiltal_mots_cles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('publié', 'Publié'), ('rejeté', 'Rejeté')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('publié', 'Publié'), ('rejeté', 'Rejeté')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('publié', 'Publié'), ('rejeté', 'Rejeté')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='outiltal',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('publié', 'Publié'), ('rejeté', 'Rejeté')], default='brouillon', max_length=20),
        ),
    ]
