# Generated by Django 5.1.7 on 2025-07-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='leave_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='leave_request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
    ]
