# Generated by Django 5.1.7 on 2025-04-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_start', 'title'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='date_start',
        ),
    ]
