# Generated by Django 5.1.7 on 2025-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Réalisé'), ('planned', 'Planifié')], default='ongoing', max_length=20),
        ),
    ]
