# Generated by Django 5.1.7 on 2025-04-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
    ]
