# Generated by Django 5.1.7 on 2025-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('En cours', 'ongoing'), ('Réalisé', 'completed'), ('Planifié', 'planned')], default='ongoing', max_length=20),
        ),
    ]
