# Generated by Django 5.1.7 on 2025-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
