# Generated by Django 5.1.7 on 2025-05-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Réalisé'), ('planned', 'Planifié')], default='ongoing', max_length=20),
        ),
    ]
