# Generated by Django 5.1.7 on 2025-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre descriptif de la ressource', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(help_text='Description détaillée de la ressource', verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('type_acces', models.CharField(choices=[('public', 'Public'), ('privé', 'Privé'), ('restreint', 'Accès restreint')], default='public', max_length=20, verbose_name="Type d'accès")),
                ('lien_acces', models.URLField(blank=True, null=True, verbose_name="Lien d'accès")),
                ('auteur', models.CharField(max_length=100, verbose_name='Auteur')),
                ('langue', models.CharField(default='arabe', help_text='Langue principale du corpus', max_length=50, verbose_name='Langue du corpus')),
                ('taille', models.IntegerField(help_text='Taille en nombre de mots ou de documents', verbose_name='Taille du corpus')),
                ('domaine', models.CharField(help_text='Domaine principal du corpus', max_length=50, verbose_name="Domaine d'étude")),
                ('format', models.CharField(help_text='Format du corpus (ex: TXT, CSV, JSON)', max_length=10, verbose_name='Format')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cours',
            name='est_public',
        ),
        migrations.AddField(
            model_name='cours',
            name='lien_acces',
            field=models.URLField(blank=True, null=True, verbose_name="Lien d'accès"),
        ),
        migrations.AddField(
            model_name='outiltal',
            name='langues',
            field=models.CharField(default='arabe', help_text="Langues supportées par l'outil, séparées par des virgules", max_length=255, verbose_name='Langues supportées'),
        ),
        migrations.AlterField(
            model_name='outiltal',
            name='lien_acces',
            field=models.URLField(blank=True, null=True, verbose_name="Lien d'accès"),
        ),
    ]
