# Generated by Django 5.1.7 on 2025-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_corpus_remove_cours_est_public_cours_lien_acces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='resume_auto',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé généré automatiquement'),
        ),
    ]
