# Generated by Django 5.1.7 on 2025-04-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_cours_resume_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='resume_auto',
        ),
    ]
