# Generated by Django 5.1.7 on 2025-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_cours_resume_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='mots_cles',
            field=models.CharField(max_length=255, null=True, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='cours',
            name='mots_cles',
            field=models.CharField(max_length=255, null=True, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='outiltal',
            name='mots_cles',
            field=models.CharField(max_length=255, null=True, verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mots_cles',
            field=models.CharField(max_length=255, null=True, verbose_name='Mots-clés'),
        ),
    ]
